name: Bug Report
description: Report an issue you've encountered.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to report this bug! You gotta make sure these before reporting...
        - You are running the latest version of Connector and its dependencies.
        - This bug wasn't already reported or being closed.
  - type: input
    id: description
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: input
    id: intended-behavior
    attributes:
      label: Intended behavior
      description: "The expected behavior."
  - type: input
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: "What actually happens to your game."
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: |
        How do you trigger this bug? Please walk us through it step by step.
        If applicable, add screenshots to help explain your problem.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Logs
      description: |
        If applicable (crash, error output in console), please provide your crash report or latest.log
        To upload logs, use an external site to post the crash report, such as [**MCLogs (Recommended)**](https://mclo.gs/), [Ubuntu Pastebin](https://paste.ubuntu.com/), or [Pastebin](http://pastebin.com/)
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context about the problem here, such as the modpack you're playing or other mods that might be causing this bug."