name: Mod Malfunction
description: Report one or more malfunctioning mod(pack)s.
labels: [compat, malfunction, pending]
body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to report this incompatibility! Before opening an issue, please make sure that:
        - You are running the latest version of Connector and its dependencies.
        - This bug wasn't already reported, fixed in the dev build or closed as not planned.
  - type: input
    id: mod
    attributes: 
      label: Mod Name(s)
      description: "Name of the problematic mod."
      placeholder: "Mod Name"
    validations:
      required: true
  - type: input
    id: homepage
    attributes: 
      label: Mod Homepage(s)
      description: "A link to the mod's homepage. This can be its CurseForge, Modrinth, Github repository or something else."
      placeholder: "https://example.com"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        How do you trigger this bug? Please walk us through it step by step.
        If applicable, add screenshots to help explain your problem. In case the mod crashes the game without
        ever loading, feel free to skip this step.
      value: |
        1.
        2.
        3.
        ...
  - type: input
    id: intended-behavior
    attributes:
      label: Intended behavior
      description: "The expected behavior."
  - type: input
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: "What actually happens to your game."
  - type: input
    id: logs
    attributes:
      label: Logs
      description: |
        If applicable (crash, error output in console), please provide your crash report.
        Otherwise, we recommend uploading the debug.log found in your `.minecraft/logs` directory.
        To upload logs, use an external site to upload the crash report, such as [**MCLogs (Recommended)**](https://mclo.gs/), [Paste.GG](https://paste.gg/), or [Pastebin](http://pastebin.com/)
        You can upload additional files here.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context about the problem here, such as the modpack you're playing or other mods that might be causing this bug."